### ISSUE TITLE
Noon vs. midnight mixup

### ISSUE THREAD

**Issue by graue** [recursecenter/community#291]
Looks like times between 12pm and 12:59pm are showing as 12am to 12:59am instead:

![Screenshot showing the problem. Post times go from 11am to 12am to 1pm.](https://cloud.githubusercontent.com/assets/1730853/6242825/054b8290-b6eb-11e4-95b4-6b62028657b9.png)

**Comment by zachallaun** [comment]
It's such a good idea to role your own datetime formatting, I thought.

It'll be easy because it's only used in a few places, I thought.

:disappointed:

I know how to fix it though, and will do so soon.
