### ISSUE TITLE
Feature request allow subscribe me to first post in thread

### ISSUE THREAD

**Issue by yaelelmatad** [recursecenter/community#303]
I like being automatically subscribed to new threads but I end up unsubscribing from most because they don't apply to me. Can there be a way to subscribe automatically to the first post in a new thread then immediately unsubscribed until I opt in?

**Comment by zachallaun** [comment]
Yep! Uncheck the field "Subscribe me to new threads created in subforums I'm subscribed to" in [your settings](https://community.recurse.com/settings). With this field unchecked, you'll receive a notification when a new thread is created, but you won't get any follow-ups until you explicitly subscribe to that thread.

**Comment by zachallaun** [comment]
Going to close this issue. Please re-open in the solution above isn't what you actually want. =)

**Comment by yaelelmatad** [comment]
Ok, you are probably right and I am slow. I don't use community much (mostly just via email) so I assumed broadcast meant something more than "when you write the first post in a thread" which is now what I understand it to mean?   I assumed clicking that option would essentially get me NO emails.  Sorry for the confusion @zachallaun

**Comment by zachallaun** [comment]
This is definitely not your fault – there are (unfortunately) a number of confusing things in Community that we'd like to fix. Broadcasting and subscribing sort of work together, but in a potentially confusing way. Whenever you make a post, including the first post of a new thread, you choose which broadcast groups will receive the message. Subscribers to a particular subforum or thread is one such broadcast group, and others include groups like "Faculty" or "Summer 2012."

Unchecking that field though will do what you want. Broadcasting to subforum subscribers is the default behavior, and we're planning to make it impossible to _not_ broadcast to subscribers in the near future.
