### ISSUE TITLE
Hello from Nepal !

### ISSUE THREAD

**Issue by bishisht** [recursecenter/community#339]
Hello. I am very interested in joining this community. I have found out about this almost 2 minutes ago. :) Didn't found anyplace to contact you guys for asking when will the RC Start starts again? 

Sorry, if I have broken any rules.

**Comment by zachallaun** [comment]
Hi @bishisht! RC Start is on a permanent hiatus at the moment — I'm  not sure when we're going to have more information about it. In the meantime, you can learn more about RC [on our site](https://www.recurse.com/), and if you have any questions about the application process, you can email admissions@recurse.com.

All the best,
Zach
