### ISSUE TITLE
New region: Asia

### ISSUE THREAD

**Issue by gnclmorais** [recursecenter/community#346]
Hi folks! First of all, sorry if this is the wrong place to place this suggestion.

I’ve noticed we have a few regions on Community, which are great for people to spontaneously reach out to other Recursers around the world when we move around. I’ve noticed there is no section for **Asia** and I think it would be a good addition. 😃 

P.S.: I’ll be around Japan in March, so if anyone wants to meet, ping me! 📬

**Comment by carld** [comment]
Just to +1 this... and suggest calling it "Asia/Pacific" to get global coverage in by the community regions.

Refer the recent zulip topic stream:Small+Questions topic:Community+-+Asia/Pacific?

**Comment by carld** [comment]
Not sure if anyone has see this and thought about it, would you mind @jollysonali ? My thoughts are that an Asia/Pacific region in community would cover off the rest of the world not currently included by another region in community. Even those there's only a few of us in India/Singapore/Aus/NZ it might be nice for RCers traveller to those parts of the world.  Singapore is a major travel hub in this region, so an RCer with a stopover in this part of the world might make it to a meet up
Thanks!

**Comment by davidbalbert** [comment]
We should do this. I get to it this week. Thanks for being patient with us!

**Comment by davidbalbert** [comment]
We now have one :). Thanks for reporting.
