### ISSUE TITLE
Thread isn't rendering, likely due to unprintable unicode character.

### ISSUE THREAD

**Issue by malisper** [recursecenter/community#360]
When I attempt to load the thread https://community.recurse.com/t/visiting-sf-escape-room/3642, the page never loads.

In the JS console, I see the error message "Uncaught Error: Invalid JSON string:". When I validate the JSON, it points out there is a unprintable unicode character (codepoint 8232) in one of the messages. This appears to be braking the JSON parser.

**Comment by corintxt** [comment]
Yes, I tried to read the main welcome thread but it's currently offline showing the same error...

**Comment by davidbalbert** [comment]
I'll fix this today. Thanks for reporting.

**Comment by davidbalbert** [comment]
Turns out this was an issue with the Google Closure JSON parser. We switched to using `JSON.parse` in #363 and now everything works.
