### ISSUE TITLE
Sending an email to the list

### ISSUE THREAD

**Issue by hypotext** [recursecenter/community#369]
Hi! I wasn't clear on if an email is sent to the list (e.g. `LOCATION@lists.community.recurse.com`), does it go to subscribers of that subforum? I just sent an email to that list, not using the forum GUI. I don't see it as a thread in the particular subforum but I also haven't received an email bounce notification. Any clarification would be appreciated.

**Comment by davidbalbert** [comment]
You unfortunately can't start a thread via email. You have to start it on the web. Responding by email works, but that's it :/

**Comment by hypotext** [comment]
Ok, thanks @davidbalbert.
