### ISSUE TITLE
New Region: Latin America or South America

### ISSUE THREAD

**Issue by xmunoz** [recursecenter/community#387]
I recently moved to Ecuador, and noticed that Community doesn't have a Latin America or South America region. I'd really love to connect with other Recursers in the region about the tech scene, conferences, open source, internationalization/translation, etc.

Please consider adding this region so latino recursers can network :llama:

**Comment by davidbalbert** [comment]
Great idea. Just added a Latin America forum. Thanks for the suggestion!
